version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 3000:3000
    container_name: nodev1
    command: node index.js
    depends_on:
      mysql_db:
          condition: service_healthy
    env_file:
      - .env


  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nodev1
      MYSQL_DATABASE: node_api
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 3

volumes:
  db_data: